CREATE TABLE NACOS.CONFIG_INFO
(
    ID           NUMBER(20) NOT NULL PRIMARY KEY,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(255),
    CONTENT      CLOB          NOT NULL,
    MD5          VARCHAR(32),
    GMT_CREATE   DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    GMT_MODIFIED DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)            DEFAULT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    TENANT_ID    VARCHAR(128)           DEFAULT NULL,
    C_DESC       VARCHAR(256)           DEFAULT NULL,
    C_USE        VARCHAR(64)            DEFAULT NULL,
    EFFECT       VARCHAR(64)            DEFAULT NULL,
    TYPE         VARCHAR(64)            DEFAULT NULL,
    C_SCHEMA     CLOB
);
ALTER TABLE NACOS.CONFIG_INFO
    ADD CONSTRAINT UK_CONFIGINFO_DATAGROUPTENANT UNIQUE (DATA_ID, GROUP_ID, TENANT_ID);

CREATE SEQUENCE NACOS.SEQ_CONFIG_INFO
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.CONFIG_INFO_AGGR
(
    ID           NUMBER(20) NOT NULL PRIMARY KEY,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(255)  NOT NULL,
    DATUM_ID     VARCHAR(255)  NOT NULL,
    CONTENT      CLOB          NOT NULL,
    GMT_MODIFIED DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    TENANT_ID    VARCHAR(128)
);

ALTER TABLE NACOS.CONFIG_INFO_AGGR
    ADD CONSTRAINT UK_AGGR_DATAGROUPTENANTDATUM UNIQUE (DATA_ID, GROUP_ID, TENANT_ID, DATUM_ID);

CREATE SEQUENCE NACOS.SEQ_CONFIG_INFO_AGGR
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.CONFIG_INFO_BETA
(
    ID           NUMBER(20) NOT NULL PRIMARY KEY,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(128)  NOT NULL,
    APP_NAME     VARCHAR(128)  DEFAULT NULL,
    CONTENT      CLOB          NOT NULL,
    BETA_IPS     VARCHAR(1024) DEFAULT NULL,
    MD5          VARCHAR(32)   DEFAULT NULL,
    GMT_CREATE   DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    GMT_MODIFIED DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50) DEFAULT NULL,
    TENANT_ID    VARCHAR(128)
);

ALTER TABLE NACOS.CONFIG_INFO_BETA
    ADD CONSTRAINT UK_BETA_DATAGROUPTENANT UNIQUE (DATA_ID, GROUP_ID, TENANT_ID);

CREATE SEQUENCE NACOS.SEQ_CONFIG_INFO_BETA
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.CONFIG_INFO_TAG
(
    ID           NUMBER(20) NOT NULL PRIMARY KEY,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(128)  NOT NULL,
    TENANT_ID    VARCHAR(128),
    TAG_ID       VARCHAR(128)  NOT NULL,
    APP_NAME     VARCHAR(128)  DEFAULT NULL,
    CONTENT      CLOB          NOT NULL,
    MD5          VARCHAR(32),
    GMT_CREATE   DATE    DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    GMT_MODIFIED DATE    DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)  DEFAULT NULL
);

ALTER TABLE NACOS.CONFIG_INFO_TAG
    ADD CONSTRAINT UK_TAG_DATAGROUPTENANTTAG UNIQUE (DATA_ID, GROUP_ID, TAG_ID);

CREATE SEQUENCE NACOS.SEQ_CONFIG_INFO_TAG
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.CONFIG_TAGS_RELATION
(
    ID        NUMBER(20) NOT NULL PRIMARY KEY,
    TAG_NAME  VARCHAR(128)  NOT NULL,
    TAG_TYPE  VARCHAR(64) DEFAULT NULL,
    DATA_ID   VARCHAR(255)  NOT NULL,
    GROUP_ID  VARCHAR(128)  NOT NULL,
    TENANT_ID VARCHAR(128),
    NID       NUMBER(20) NOT NULL
);

ALTER TABLE NACOS.CONFIG_TAGS_RELATION
    ADD CONSTRAINT UK_RELATION_CONFIGIDTAG UNIQUE (ID, TAG_NAME, TAG_TYPE);

CREATE SEQUENCE NACOS.SEQ_CONFIG_TAGS_RELATION
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;


CREATE TABLE NACOS.GROUP_CAPACITY
(
    ID                NUMBER(20)  NOT NULL,
    GROUP_ID          VARCHAR(128)   NOT NULL,
    QUOTA             NUMBER(10) NOT NULL,
    USAGE             NUMBER(10) NOT NULL,
    MAX_SIZE          NUMBER(10) NOT NULL,
    MAX_AGGR_COUNT    NUMBER(10) NOT NULL,
    MAX_AGGR_SIZE     NUMBER(10) NOT NULL,
    MAX_HISTORY_COUNT NUMBER(10) NOT NULL,
    GMT_CREATE        DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    GMT_MODIFIED      DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE NACOS.GROUP_CAPACITY
    ADD CONSTRAINT UK_GROUP_ID UNIQUE (GROUP_ID);

CREATE SEQUENCE NACOS.SEQ_GROUP_CAPACITY
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.HIS_CONFIG_INFO
(
    ID           NUMBER(20) NOT NULL PRIMARY KEY,
    NID          NUMBER(20) NOT NULL,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(128)  NOT NULL,
    APP_NAME     VARCHAR(128)  DEFAULT NULL,
    CONTENT      CLOB          NOT NULL,
    MD5          VARCHAR(32)            DEFAULT NULL,
    GMT_CREATE   DATE   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    GMT_MODIFIED DATE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)  DEFAULT NULL,
    OP_TYPE      VARCHAR(10)  DEFAULT NULL,
    TENANT_ID    VARCHAR(128)
);

CREATE SEQUENCE NACOS.SEQ_HIS_CONFIG_INFO
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.TENANT_CAPACITY
(
    ID                NUMBER(20) NOT NULL PRIMARY KEY,
    TENANT_ID         VARCHAR(128)   NOT NULL,
    QUOTA             NUMBER(10) NOT NULL,
    USAGE             NUMBER(10) NOT NULL,
    MAX_SIZE          NUMBER(10) NOT NULL,
    MAX_AGGR_COUNT    NUMBER(10) NOT NULL,
    MAX_AGGR_SIZE     NUMBER(10) NOT NULL,
    MAX_HISTORY_COUNT NUMBER(10) NOT NULL,
    GMT_CREATE        DATE DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED      DATE DEFAULT SYSDATE NOT NULL
);


ALTER TABLE NACOS.TENANT_CAPACITY
    ADD CONSTRAINT UK_TENANT_ID UNIQUE (TENANT_ID);

CREATE SEQUENCE NACOS.SEQ_TENANT_CAPACITY
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.TENANT_INFO
(
    ID            NUMBER(20) NOT NULL,
    KP            VARCHAR(128)  NOT NULL,
    TENANT_ID     VARCHAR(128),
    TENANT_NAME   VARCHAR(128),
    TENANT_DESC   VARCHAR(256) DEFAULT NULL,
    CREATE_SOURCE VARCHAR(32)  DEFAULT NULL,
    GMT_CREATE    NUMBER(20) NOT NULL,
    GMT_MODIFIED  NUMBER(20) NOT NULL,
    CONSTRAINT PK_TENANT_INFO PRIMARY KEY (ID)
);


ALTER TABLE NACOS.TENANT_INFO
    ADD CONSTRAINT UK_TENANT_INFO_KPTENANTID UNIQUE (KP, TENANT_ID);

CREATE SEQUENCE NACOS.SEQ_TENANT_INFO
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE NACOS.USERS
(
    USERNAME VARCHAR(50)  NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(500) NOT NULL,
    ENABLED  VARCHAR(1)  NOT NULL
);


CREATE TABLE NACOS.ROLES
(
    USERNAME VARCHAR(50) NOT NULL,
    ROLE     VARCHAR(50) NOT NULL
);

CREATE TABLE NACOS.PERMISSIONS
(
    ROLE     VARCHAR(50)  NOT NULL,
    "RESOURCE" VARCHAR(255) NOT NULL,
    ACTION   VARCHAR(8)   NOT NULL
);

INSERT INTO NACOS.USERS (USERNAME, PASSWORD, ENABLED) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

INSERT INTO NACOS.ROLES (USERNAME, ROLE) VALUES ('nacos', 'ROLE_ADMIN');

